### ISSUE TITLE
Deployment image.openshift.io/triggers ImageStreamTag is not updated during restore 

### ISSUE THREAD

**Issue by justin-cohesity** [konveyor/openshift-velero-plugin#103]
While testing with an example httpd app with both OCP 4.7 and 4.8, it seems on restore everything seems to be correct with respect to the new namespace/project, except for this one Deployment annotation.

As an example (deployment/httpd-sample):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/sclorg/httpd-ex.git
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"httpd-sample:latest","namespace":"justin-build-test-5"},"fieldPath":"spec.template.spec.containers[?(@.name==\"httpd-sample\")].image","pause":"false"}]'
```
If restoring to say justin-build-[test-5](https://issues.redhat.com/browse/test-5)-restore, the image.openshift.io/triggers is not updated and still has justin-build-[test-5](https://issues.redhat.com/browse/test-5) as the namespace.

Because of this deployment.apps and pod are in a bad state after restore.

I tested with both velero 1.4 and 1.6.3 and the openshift plugin.

In order to repo:

Install one of the below from the sample applications within the OpenShift WebUI:

- Add
- Create applications using samples
- View all samples
- Httpd <or> Basic NodeJS
- Create

Backup and restore via Velero /w the openshift-velero-plugin to a new namespace
